CREATE TABLE IF NOT EXISTS "chat_admins" (
    
);

CREATE TABLE IF NOT EXISTS "messages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_message_id bigint NOT NULL,
    telegram_chat_id bigint NOT NULL,
    telegram_sender_id bigint NOT NULL,
    sender_name varchar(255) NOT NULL,
    sender_username varchar(255),
    content_type varchar(128) NOT NULL,
    content TEXT,
    sent_at timestamptz NOT NULL DEFAULT NOW(),
    moderation_verdict varchar(128) 
);