CREATE TABLE IF NOT EXISTS "messages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_message_id bigint NOT NULL,
    telegram_chat_id bigint NOT NULL,
    telegram_sender_id bigint NOT NULL,
    telegram_chat_title varchar(255),
    sender_name varchar(255) NOT NULL,
    sender_username varchar(255),
    content_type varchar(128) NOT NULL,
    content TEXT,
    sent_at timestamptz NOT NULL DEFAULT NOW(),
    moderation_verdict varchar(128) 
);

CREATE TABLE IF NOT EXISTS "bans" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id bigint NOT NULL,
    telegram_chat_id bigint NOT NULL,
    telegram_message_id bigint,
    telegram_admin_id bigint NOT NULL,
    origin_message_content TEXT,  
    is_global BOOLEAN DEFAULT TRUE,
    reason varchar(128) NOT NULL,
    ban_date timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bans_telegram_user_id_idx ON bans (telegram_user_id);

CREATE INDEX IF NOT EXISTS messages_telegram_sender_id_idx ON messages (telegram_sender_id);